apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "auth-service.fullname" . }}-sync
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-cluster-store
    kind: ClusterSecretStore
  target:
    name: {{ include "auth-service.fullname" . }}-auth-secret # 生成的 Secret 名字
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: "ecommerce/prod/secrets" # 對應 Terraform 裡的 Secret Name