apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "frontend.fullname" . }}-ingress
  namespace: default
  annotations:
    # 告訴 AWS Load Balancer Controller 建立一個 internet-facing 的 ALB
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb # 務必確認你的 Controller 版本支援這個欄位
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "frontend.fullname" . }}-service
                port:
                  number: 80