server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # # 當看到 /api/auth，就轉發給 auth-service 容器
    # location /api/auth/ {
    #     proxy_pass http://auth-service:8000/; # 注意最後的斜線
    #     proxy_set_header Host $host;
    # }

    # # 當看到 /api/order，就轉發給 order-service 容器
    # location /api/order/ {
    #     proxy_pass http://order-service:8001/;
    #     proxy_set_header Host $host;
    # }

    location /api/auth {
        # proxy_pass 後面的斜線保留，這代表「路徑替換」
        # 它會把 /api/auth/login 轉發給後端時變成 /login
        proxy_pass http://auth-service:8000/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/order {
        proxy_pass http://order-service:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}