apiVersion: v1
kind: Service
metadata:
  name: {{ include "order-service.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    app: {{ include "order-service.name" . }}