replicaCount: 2

image:
  # 這是你 ECR 的路徑 (不含 Tag)
  repository: "prod-ecommerce/frontend"
  registry: "851725371209.dkr.ecr.ap-northeast-1.amazonaws.com"
  pullPolicy: IfNotPresent
  tag: "v54-aa6ae4b"

service:
  type: NodePort
  port: 80

containerPort: 3000